@extends('layouts.master')

@section('content')
@include('modules.header')
@include('modules.hud', ['title' => 'Terms and Conditions', 'icon' => 'briefcase', 'user_name' => $user_name])
@include('modules.banner', ['title' => 'Terms and Conditions'])
<div class="box bg-1">
	<div class="box measure bg-0 border-left border-bottom-0">
		@include('modules.section_divide', ['name' => 'This site is owned by My After School Programs, Inc. (“Corp.”). PLEASE READ THE TERMS AND CONDITIONS and PRIVACY POLICY CAREFULLY BEFORE USING THIS SITE.'])
		<div class="box box-pad-0 bg-0 border-bottom-0">By using this site, you signify your express consent and agreement to these Terms and Conditions and Privacy Policy without modification. If you do not agree to these Terms and Conditions or Privacy Policy, please do not use this site. We reserve the right, at our discretion, to change, add, remove or otherwise modify portions of these Terms and Conditions or Privacy Policy at any time. Please check these Terms and Conditions and Privacy Policy periodically for changes. Your continued use of this site following the posting of changes shall signify your acceptance of such changes.</div>
		<div class="box box-pad-0 bg-0 border-bottom-0">If you use this site, you are responsible for maintaining the confidentiality of membership account information, usernames, passwords, Ids, credit card information(?),  that may be required to use the site from time to time, and for restricting access to your computer or other devices, and you agree that you are responsible for all activity that occurs under or with the use of your Account Information (including, without limitation, usernames and passwords).</div>
		<div class="box box-pad-0 bg-0 border-bottom-0">Corp. reserves the right in their sole discretion to refuse access to the site or services provided through it, terminate accounts and usage rights, cancel registrations made through the site. (Duplicative of provisions contained in Privacy Site – see changes there and incorporate them here)</div>
		<div class="box box-pad-0 bg-0 border-bottom-0">Know your schedule.  By registering for a class on this site, you are actively reserving a space for your child to participate, and agree to the class schedule which is provided to you to prior to your payment.  No refunds/credits/make-ups can be given for missed classes.</div>
		<div class="box box-pad-0 bg-0 border-bottom-0">Occasionally, session schedules are subject to cancelations due to weather and /or unforeseen facility circumstances beyond our control.  To enable the completion of a full session, we have placed make-up dates (same time/day of week as your normal schedule) on the weeks following the end of the series.  THESE MAKE UP DATES ARE TO BE CONSIDERED PART OF THE CLASS SCHEDULE, and no refunds/credits/ make-ups can be given for a missed make-up class.</div>
		<div class="box box-pad-0 bg-0 border-bottom-0">Make up dates are intended only for the purpose of rescheduling classes due to our class cancelations.  They are not intended for personal make-ups for missed classes.</div>
		<div class="box box-pad-0 bg-0 border-bottom-0">Individuals calling after missing an “in-person”  sign up are directed to the website to complete their registration.  A 24 hour window is set from the time of individual’s call.  Missing this window will remove the ability to sign up, and will jeopardize the place that has been held.  If the individual still wants this spot, they must call back to see if the spot is still available, at which time, a second 24 hour window can be started, if a spot is still available.  Corp. will not be responsible for lost spots due to customers failing to register on time.</div>
		<div class="box box-pad-0 bg-0 border-bottom-0">CORP. DOES NOT WARRANT THAT THE SITE WILL BE UNINTERRUPTED OR ERROR-FREE, THAT DEFECTS WILL BE CORRECTED, OR ARE FREE OF VIRUSES OR OTHER HARMFUL COMPONENTS. YOU ASSUME THE ENTIRE COST OF ALL NECESSARY SERVICING, REPAIR OR CORRECTION (Duplicative of provisions contained in Privacy Site – see changes there and incorporate them here).</div>
		<div class="box box-pad-0 bg-0 border-bottom-0">We do not make any representations or warranties as to the security of any information you  might be requested to give any third party (including, without limitation, credit card and other personal information), and you hereby irrevocably waive any claim against us with respect to such sites and third party content.  (Duplicative of provisions contained in Privacy Site – see changes there and incorporate them here)</div>
		<div class="box box-pad-0 bg-0 border-bottom-0">All financial transactions on this site occur through PayPal and as such, Corp. has no direct access to your credit card info.  In no event shall Corp., and other affiliated companies, organizations and/or sponsors be liable for any breach in transaction security arising out of or relating to any purchase or attempt to purchase services. (Duplicative of provisions contained in Privacy Site – see changes there and incorporate them here)</div>
		@include('modules.section_divide', ['name' => 'Indemnification']) 
		<div class="box box-pad-0 bg-0 border-bottom-0">You are entirely responsible for maintaining the confidentiality and security of your Account Information and for all activities that occur under your account. You agree to indemnify, defend and hold harmless Corp. and other affiliated companies/organizations and sponsors and their respective officers, directors, employees and agents from and against any third-party claims, demands, actions, suits, proceedings, liabilities, damages, losses, judgments and expenses (including, but not limited to, the costs of collection, reasonable attorney’s fees and other reasonable costs of defense or enforcing your obligations hereunder) resulting from or arising out of any breach of any of your representations or misuse of this site. You shall use your best efforts to cooperate with us in the defense of any claim. (Duplicative of provisions contained in Privacy Site – see changes there and incorporate them here)</div>
	</div>
	<div class="box box-pad-0 bg-0"></div>
</div>
@stop
